export const SET_TRACK_REQUEST = "SET_TRACK_REQUEST";
export const SET_TRACK_ERROR = "SET_TRACK_ERROR";
export const SET_TRACK_SUCCESS = "SET_TRACK_SUCCESS";

export const SET_IMAGE_REQUEST = "SET_IMAGE_REQUEST";
export const SET_IMAGE_ERROR = "SET_IMAGE_ERROR";
export const SET_IMAGE_SUCCESS = "SET_IMAGE_SUCCESS";