export const FETCH_SONGS = 'FETCH_SONGS';
export const SONGS_SET_ERROR = "SONGS_SET_ERROR";
export const SONGS_SET_RESULT = "SONGS_SET_RESULT";
export const SONGS_RESET = "SONGS_RESET";
export const SONGS_LOADING = "SONGS_LOADING";
export const SONGS_LOADING_SUCCESS = "SONGS_LOADING_SUCCESS";