export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST";
export const SET_PLAYLISTS_RESULT = "SET_PLAYLISTS_RESULT";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";
export const ADD_TO_PLAYLIST_SUCCESS = "ADD_TO_PLAYLIST_SUCCESS";
export const ADD_TO_PLAYLIST_ERROR = "ADD_TO_PLAYLIST_ERROR";
export const REMOVE_TO_PLAYLIST_SUCCESS = "REMOVE_TO_PLAYLIST_SUCCESS";
export const REMOVE_TO_PLAYLIST_ERROR = "REMOVE_TO_PLAYLIST_ERROR";